"""
Train the discard action model from grouped discard dataset.

Loads the dataset generated by tools/generate_discard_data.py,
trains an MLP classifier on the binary near-optimal labels,
and saves the trained model.

Usage:
  python train_discard_model.py [--data PATH] [--output PATH] [--verbose]
"""

import argparse
import os
import sys
import json
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
from gin_rummy.discard_action_model import train_discard_model, LearnedDiscardModel
from gin_rummy.discard_action_features import DISCARD_FEATURE_DIM


def main():
    parser = argparse.ArgumentParser(description="Train discard action model")
    parser.add_argument("--data", type=str, default=None,
                        help="Input data path (default: models/discard_action_data.npz)")
    parser.add_argument("--output", type=str, default=None,
                        help="Output model path (default: models/discard_action_model.pkl)")
    parser.add_argument("--results", type=str, default=None,
                        help="Output results JSON (default: models/discard_action_results.json)")
    parser.add_argument("--verbose", action="store_true",
                        help="Print training progress")
    args = parser.parse_args()

    project_root = os.path.dirname(os.path.abspath(__file__))
    data_path = args.data or os.path.join(project_root, "models", "discard_action_data.npz")
    model_path = args.output or os.path.join(project_root, "models", "discard_action_model.pkl")
    results_path = args.results or os.path.join(project_root, "models", "discard_action_results.json")

    print("=" * 60)
    print("  DISCARD ACTION MODEL TRAINING")
    print("=" * 60)
    print(f"  Data:    {data_path}")
    print(f"  Output:  {model_path}")
    print("=" * 60)

    # Load data
    data = np.load(data_path, allow_pickle=True)
    X = data['X']
    utilities = data['utilities']
    group_ids = data['group_ids']
    labels = data['labels']

    n_groups = len(np.unique(group_ids))
    pos_rate = np.mean(labels)

    print(f"  Samples:             {len(X):,}")
    print(f"  Groups:              {n_groups:,}")
    print(f"  Feature dim:         {X.shape[1]}")
    print(f"  Near-optimal rate:   {pos_rate:.3f}")
    print(f"  Avg cands/group:     {len(X) / max(n_groups, 1):.1f}")
    print()

    # Group-aware train-test split (keep entire groups together)
    unique_groups = np.unique(group_ids)
    rng = np.random.RandomState(42)
    rng.shuffle(unique_groups)

    split_idx = int(0.8 * len(unique_groups))
    train_groups = set(unique_groups[:split_idx])
    test_groups = set(unique_groups[split_idx:])

    train_mask = np.array([g in train_groups for g in group_ids])
    test_mask = np.array([g in test_groups for g in group_ids])

    X_train, y_train = X[train_mask], labels[train_mask]
    X_test, y_test = X[test_mask], labels[test_mask]
    group_test = group_ids[test_mask]
    utils_test = utilities[test_mask]

    print(f"  Train samples:       {len(X_train):,}")
    print(f"  Test samples:        {len(X_test):,}")
    print(f"  Train groups:        {len(train_groups):,}")
    print(f"  Test groups:         {len(test_groups):,}")
    print()

    # Train model
    print("  Training MLP classifier...")
    start = time.time()
    model = train_discard_model(
        X_train, y_train,
        hidden_layers=(128, 64, 32),
        max_iter=500,
        random_state=42,
        verbose=args.verbose,
    )
    train_time = time.time() - start
    print(f"  Training time: {train_time:.1f}s")
    print()

    # Evaluate on test set — flat metrics
    from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, brier_score_loss

    y_pred_proba = model.score_candidates(X_test)
    y_pred = (y_pred_proba > 0.5).astype(np.float32)

    test_acc = accuracy_score(y_test, y_pred)
    test_auc = roc_auc_score(y_test, y_pred_proba)
    test_brier = brier_score_loss(y_test, y_pred_proba)
    y_proba_clamped = np.clip(y_pred_proba, 1e-7, 1 - 1e-7)
    test_logloss = log_loss(y_test, y_proba_clamped)

    print(f"  === Flat Metrics ===")
    print(f"  Test Accuracy:   {test_acc:.4f}")
    print(f"  Test AUC:        {test_auc:.4f}")
    print(f"  Test Brier:      {test_brier:.4f}")
    print(f"  Test LogLoss:    {test_logloss:.4f}")
    print()

    # Group-aware metrics: top-1 accuracy and average regret
    top1_correct = 0
    total_groups_tested = 0
    total_regret = 0.0

    for gid in np.unique(group_test):
        mask = group_test == gid
        group_proba = y_pred_proba[mask]
        group_labels = y_test[mask]
        group_utils = utils_test[mask]

        # Top-1: does the model's top choice have label=1?
        model_choice = np.argmax(group_proba)
        if group_labels[model_choice] > 0.5:
            top1_correct += 1

        # Regret: utility of best vs utility of model's choice
        best_util = np.max(group_utils)
        chosen_util = group_utils[model_choice]
        regret = best_util - chosen_util
        total_regret += regret
        total_groups_tested += 1

    top1_acc = top1_correct / max(total_groups_tested, 1)
    avg_regret = total_regret / max(total_groups_tested, 1)

    print(f"  === Group-Aware Metrics ===")
    print(f"  Top-1 Accuracy:  {top1_acc:.4f} ({top1_correct}/{total_groups_tested})")
    print(f"  Avg Regret:      {avg_regret:.4f}")
    print()

    # Save model
    model.save(model_path)
    print(f"  Model saved to: {model_path}")

    # Save results
    results = {
        'total_samples': len(X),
        'total_groups': n_groups,
        'train_samples': len(X_train),
        'test_samples': len(X_test),
        'train_groups': len(train_groups),
        'test_groups': len(test_groups),
        'feature_dim': int(X.shape[1]),
        'near_optimal_rate': round(float(pos_rate), 4),
        'test_accuracy': round(test_acc, 4),
        'test_auc': round(test_auc, 4),
        'test_brier': round(test_brier, 4),
        'test_logloss': round(test_logloss, 4),
        'top1_accuracy': round(top1_acc, 4),
        'avg_regret': round(float(avg_regret), 4),
        'train_time_sec': round(train_time, 1),
        'hidden_layers': [128, 64, 32],
    }

    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"  Results saved to: {results_path}")

    print()
    print("=" * 60)
    print("  TRAINING COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
