"""
Train the knock action model from knock-decision dataset.

Loads the dataset generated by tools/generate_knock_data.py,
trains an MLP classifier on the binary knock_better labels,
and saves the trained model.

Usage:
  python train_knock_model.py [--data PATH] [--output PATH] [--verbose]
"""

import argparse
import os
import sys
import json
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
from gin_rummy.knock_action_model import train_knock_model, LearnedKnockModel
from gin_rummy.knock_features import KNOCK_FEATURE_DIM


def main():
    parser = argparse.ArgumentParser(description="Train knock action model")
    parser.add_argument("--data", type=str, default=None,
                        help="Input data path (default: models/knock_action_data.npz)")
    parser.add_argument("--output", type=str, default=None,
                        help="Output model path (default: models/knock_action_model.pkl)")
    parser.add_argument("--results", type=str, default=None,
                        help="Output results JSON (default: models/knock_action_results.json)")
    parser.add_argument("--verbose", action="store_true",
                        help="Print training progress")
    args = parser.parse_args()

    project_root = os.path.dirname(os.path.abspath(__file__))
    data_path = args.data or os.path.join(project_root, "models", "knock_action_data.npz")
    model_path = args.output or os.path.join(project_root, "models", "knock_action_model.pkl")
    results_path = args.results or os.path.join(project_root, "models", "knock_action_results.json")

    print("=" * 60)
    print("  KNOCK ACTION MODEL TRAINING")
    print("=" * 60)
    print(f"  Data:    {data_path}")
    print(f"  Output:  {model_path}")
    print("=" * 60)

    # Load data
    data = np.load(data_path, allow_pickle=True)
    X = data['X']
    point_deltas = data['point_deltas']
    knock_better = data['knock_better']

    print(f"  Samples:           {len(X):,}")
    print(f"  Feature dim:       {X.shape[1]}")
    print(f"  Knock-better rate: {np.mean(knock_better):.3f}")
    print(f"  Point delta mean:  {np.mean(point_deltas):.4f}")
    print(f"  Point delta std:   {np.std(point_deltas):.4f}")
    print()

    # Train-test split (80/20, stratified)
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test, delta_train, delta_test = train_test_split(
        X, knock_better, point_deltas, test_size=0.2, random_state=42, stratify=knock_better
    )

    print(f"  Train samples:     {len(X_train):,}")
    print(f"  Test samples:      {len(X_test):,}")
    print()

    # Train model
    print("  Training MLP classifier...")
    start = time.time()
    model = train_knock_model(
        X_train, y_train,
        hidden_layers=(64, 32, 16),
        max_iter=500,
        random_state=42,
        verbose=args.verbose,
    )
    train_time = time.time() - start
    print(f"  Training time: {train_time:.1f}s")
    print()

    # Evaluate on test set
    from sklearn.metrics import accuracy_score, log_loss, roc_auc_score, brier_score_loss

    y_pred_proba = model.predict_proba(X_test)
    y_pred = (y_pred_proba > 0.5).astype(np.float32)

    test_acc = accuracy_score(y_test, y_pred)
    test_auc = roc_auc_score(y_test, y_pred_proba)
    test_brier = brier_score_loss(y_test, y_pred_proba)
    test_logloss = log_loss(y_test, y_pred_proba)

    print(f"  Test Accuracy:   {test_acc:.4f}")
    print(f"  Test AUC:        {test_auc:.4f}")
    print(f"  Test Brier:      {test_brier:.4f}")
    print(f"  Test LogLoss:    {test_logloss:.4f}")
    print()

    # Regret: average missed point_delta on wrong predictions
    correct_mask = y_pred == y_test
    wrong_mask = ~correct_mask
    if wrong_mask.sum() > 0:
        avg_regret = np.mean(np.abs(delta_test[wrong_mask]))
    else:
        avg_regret = 0.0
    print(f"  Avg regret (wrong): {avg_regret:.4f}")

    if correct_mask.sum() > 0:
        avg_delta_correct = np.mean(np.abs(delta_test[correct_mask]))
    else:
        avg_delta_correct = 0.0
    print(f"  Avg delta (correct): {avg_delta_correct:.4f}")

    # Save model
    model.save(model_path)
    print(f"\n  Model saved to: {model_path}")

    # Save results
    results = {
        'total_samples': len(X),
        'train_samples': len(X_train),
        'test_samples': len(X_test),
        'feature_dim': int(X.shape[1]),
        'knock_better_rate': float(np.mean(knock_better)),
        'test_accuracy': round(test_acc, 4),
        'test_auc': round(test_auc, 4),
        'test_brier': round(test_brier, 4),
        'test_logloss': round(test_logloss, 4),
        'avg_regret_wrong': round(float(avg_regret), 4),
        'avg_delta_correct': round(float(avg_delta_correct), 4),
        'train_time_sec': round(train_time, 1),
        'hidden_layers': [64, 32, 16],
    }

    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"  Results saved to: {results_path}")

    print()
    print("=" * 60)
    print("  TRAINING COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
